---
- hosts: all
  become: yes
  tasks:
    - name: Install Requirements
      apt: name={{ item }} state=present
      with_items:
        - openjdk-17-jdk
        - tmux
        - htop

    - name: Compile source code.
      shell: JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 /usr/share/maven/bin/mvn package
      args:
        chdir: "/vagrant/"

    - name: Startup Progression PLC
      shell: "tmux new -d java -jar /vagrant/node/target/node-1.0.jar && tmux send script SPACE /vagrant/scripts/progression.cmd ENTER"
      when: "'progression' in ansible_hostname"

    - name: Startup HMI
      shell: "tmux new -d java -jar /vagrant/node/target/node-1.0.jar && tmux send script SPACE /vagrant/scripts/hmi.cmd ENTER"
      when: "'hmi' in ansible_hostname"
