---
- hosts: all
  become: yes
  tasks:
    - name: Install Requirements
      apt: name={{ item }} state=present
      with_items:
        - openjdk-17-jdk
        - tmux
        - htop

    - name: Configure the default Java to OpenJDK 8
      alternatives:
        name: java
        path: /usr/lib/jvm/java-17-openjdk-amd64/bin/java

    - name: Install Maven
      unarchive:
        src: "https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz"
        dest: "/usr/share/"
        remote_src: yes

    - name: Rename Maven directory
      command: mv /usr/share/apache-maven-3.9.9 /usr/share/maven

    # SSH daemon configuration.
    - name: Configure SSH daemon.
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - regexp: '^UseDNS'
          line: 'UseDNS no'
        - regexp: '^GSSAPIAuthentication'
          line: 'GSSAPIAuthentication no'

    # Vagrant SSH configuration.
    - name: Configure Vagrant .ssh directory.
      file:
        path: /home/vagrant/.ssh
        state: directory
        owner: vagrant
        group: vagrant
        mode: 0700

    - name: Get Vagrant's public key.
      get_url:
        url: https://github.com/mitchellh/vagrant/raw/master/keys/vagrant.pub
        dest: /home/vagrant/.ssh/authorized_keys
        owner: vagrant
        group: vagrant
        mode: 0600

    - name: Install VMWare Tools
      apt:
        name: open-vm-tools
        state: present

    - name: Ensure that the VM has an IP address by DHCP
      cron:
        name: "Get IP address by DHCP"
        minute: "*"
        job: "dhclient"